version: '3.7'
services:
  sample:
    container_name: cra-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3101:3100
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true
    tty: true
